name: rpi_serial
version: 0.0.1
author: Vincent Långström <example@example.com>
description: rpi_serial is a Dart library for using Serial on the Raspberry Pi.
homepage: https://github.com/vinicentus/rpi_serial.dart
environment:
  sdk: '>=2.0.0-dev.60.0 <3.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  grinder: ^0.8.0
  pedantic: ^1.1.0
  test: ^1.2.0
